### ISSUE TITLE
En tant qu'administrateur, je souhaite savoir quel modèle est utilisé par la co-propriété

### ISSUE THREAD

**Issue by Samuel-James2003** [micbelgique/TakeItOut#3]
### Description

Afficher le modèle qui a été utilisé pour une question dans les détails du prompt dans l'historique 

### Acceptance Criteria

Modèle et nombre de tokens utilisés dans chaque question

### Tasks

- [x] L'ajouter dans le détails du prompt history
- [x] L'afficher dans le front
- [ ] Séparer token GPT3 et GPT4
